# Generated by Django 5.1.4 on 2025-01-21 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('score', models.IntegerField()),
                ('date_achieved', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RaceParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('daytona', models.FloatField(default=0)),
                ('sebring', models.FloatField(default=0)),
                ('weathertech', models.FloatField(default=0)),
                ('virginia', models.FloatField(default=0)),
                ('atlanta', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
            ],
        ),
    ]
