# Generated by Django 5.1.4 on 2025-05-24 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imsa_table', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('car', models.CharField(choices=[('Porsche', 'Porsche'), ('Ferrari', 'Ferrari'), ('BMW', 'BMW'), ('Audi', 'Audi'), ('Mercedes', 'Mercedes'), ('Corvette', 'Corvette')], max_length=20)),
                ('daytona', models.FloatField()),
                ('sebring', models.FloatField()),
                ('weathertech', models.FloatField()),
                ('virginia', models.FloatField()),
                ('atlanta', models.FloatField()),
                ('total', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='RaceParticipant',
        ),
    ]
