# Generated by Django 5.1.4 on 2025-01-14 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imsa_news', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
