# Generated by Django 5.1.4 on 2025-03-30 10:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imsa_news', '0002_delete_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('url', models.URLField(verbose_name='Ссылка на статью')),
                ('excerpt', models.TextField(blank=True, verbose_name='Краткое содержание')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('image_url', models.URLField(blank=True, verbose_name='Ссылка на изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления записи')),
            ],
            options={
                'verbose_name': 'Новость IMSA',
                'verbose_name_plural': 'Новости IMSA',
                'ordering': ['-date'],
            },
        ),
    ]
